# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:R3RwG3Qf/SoAfYhzpQ==,iv:KcXYhyzKNJUhXwIY1DzNpidoEekrCRjHIOA7aPp+wjg=,tag:gpM774YR5Cj116B4xl72bA==,type:str]
    SECRET_DOMAIN2: ENC[AES256_GCM,data:2rWsUEfRxw==,iv:y8M5DkGYoSr2JOaF1BpY38dydcd5Fs4vZkIVo+Ex/R0=,tag:V2e3Qbgv2x9XNGstuhvN1w==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:fnM4pHmHib6NEeVxFA==,iv:kM1Kv8SYwIvt4UFNwmACCh6woJMuYF02XOred2YZVSA=,tag:r+68LVk/5MH2m5w9MrfAdQ==,type:str]
    SECRET_PUBLIC_IP: ENC[AES256_GCM,data:OB4EacvtRE1ZW6n1r5g=,iv:tmB+4oh7H3zwMmTgpJjsUpn0LtwG1KOWpwMDjZVX4S4=,tag:Y/N4P41cAd8PqBGILNHfJg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-11-16T02:36:49Z"
    mac: ENC[AES256_GCM,data:OCMYsv0z1JCjRnfVYLT1iC7EAFgXUSTwFDA1A1Ndb8uvCC5N4m7F0lMvvETBO1CpLK387OaEckprRPgPN0JR8bMufJV4WW7yrKWyyVDh8Xgm0BxK4FQNQ2IudDUDlYmZn/SUvtJ4cT/ULg8OrsrTMIdP1U3VzIFfkfh81e3jDOQ=,iv:NMjwraavkAHdN2irIETU4oCkm8tXdTH8JeHc+O/5DR8=,tag:XoINnCGDE8o6mlxpGu3TAw==,type:str]
    pgp:
        - created_at: "2022-10-31T03:56:25Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxnLN2eNn/kQARAApZWSd8jJJzoT/JemudIB16tmpoZ3CD+J0GdFUG9bQlt1
            lWL5MvJbju1ilRKkKQxXZwFocOxm0WWK7ilF530Xk77PyH+M+tpCTuA2XAXcf4gF
            m0xUai3KSc8suXdoQMkCEorVKx2yWJG5xqz8vxW8QJnCzRShpZzyERWoTKNe5SZD
            Wr+dDFa+Wh5+Rpa1+T5MKEOPCflJoV6SpviZJt2N8kjfeILbmGfxQcFuUIZY5Odi
            /l8JvMQy/Pt4dMNBhneFGpia5zdDMegh3+08kyjTRK3chOwrNi4ESaV96JWrjarj
            56yrTnviMm5jcpWPD6iE2lvyv4Cn2F01Hx5VFhRZo/A4AyXRgfjGNASVgmBZlr1V
            ERR6WcWFgGenOIsIpD0ukNrR6vVCfvRUtqfOzh0fjvGV/oecbfunnHlbwDxWPCSR
            gGXsIX70VwZFQjyazgklOtNn3ENpcW9p8T8fF8UAKGVAa6a4HE59e3pQcKT9KgtV
            a/mp5xvbyWic6ygAxg4/OPRu300CbE5smDPyDg+wMqA0edW2L3oSmmTNZFd5RXFf
            qurpDeTLXaKCCv+4MprHBDgVyx5ttaTLNR0Q8XRBcwm9ibf7rpGXLVAUAYN4sDIo
            O5AdN4bX7Ypx7ETupC+GwZ37mrEj9En19NGRKOl+MIPpDr7m3RSqBR/1FcjLQkXU
            ZgEJAhDH2xiax0ytl1spUfQwRFTiLUyM/XalMoVgSfhvm3PwXfSFL6FCxEse8gxq
            PRWPeQzSJOFpOwCOD7fuQ3ehgsy/ddkW8AcNX1Yz13gfdUn6Z/fNQ08o0hJUCyik
            nf3ntNf8Pg==
            =h1hj
            -----END PGP MESSAGE-----
          fp: E6D978BF2C0B69227A85D9BA04812C60A830A726
        - created_at: "2022-10-31T03:56:25Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA9Qs/eFVrZ++ARAAsujw+kf0q/rOD/unk2ujiKb6ZJ3HTFpuMFDzgDNcpJXO
            OGEzBZGzhZt/6aYmUk1J3hozC+O8HQ06kp1Xh3//rxFIo6ywlKMP8B8+XKSeeYvB
            DIxoJnlaED8nKlb/6Kt7SQapYjYqz3HbFv/nCO3plbTFQ0oI0zn6wct1YkS7pPBw
            AUPCdZuVzCXgIrpaojYUl+Tamv9UXk7sg4uRwohfzZiKNiVeDKbmDF5WylQCLx3e
            /dAP2EwZeU8bjGR8gCHo7VWojb+UhxnuxeuJJpFaHi1Ha+tXl4M+pwQQPr7ZP8Ua
            BaiZoV11fooIEPoNEUJrl9t0t5H965kYplF5hR67DvMWoCd1k2XF4Cm5UjApo1Ak
            L8evZbE3JA+Wz50bGYUA9lQFhj3eHmrlgZo3sQZ+ska2selzKoRrfm2Bby5nt76m
            7Eg7i4FTda9alEQ54COQz9bdoNx0dj6Pc4zy5TlvBpb6fiwOpYqDlME+ZROtbEHd
            Pe99NXHFfqTUFMLyJU5Ye0Ki1KRDG3I+RRCA9jd8QUdp2xeo9CqGj/A/LbS8u3/i
            Hp3aTpXr4kxud6gbYwDLPYogCoQtgpHyz4gQKPkYKHiveEAPpFL5iPMW7E7FYCNe
            FOr+qu3aZIR6xsvl/69zmkv5hr4AyhGJEWeKwhvIfuRPxl7hZ9Ixhps3g7x5pmvS
            UQHAUzomMNlpRC4WdRBhNZusEiZtl0RY7IVzX0bL1Np0qtR6XOkTlXVszM1eYYqK
            4zyFVYVyNgVN1xsTFQ5WGTZSnO7q51PR1MT1vjgTOyHoig==
            =L8Vq
            -----END PGP MESSAGE-----
          fp: 95106BD4F26A01996BDA831E6D9E63E5FF3AE8E0
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
